export const models = [
  {
    name: "GPT",
    monogram: "G",
    role: "ศูนย์บัญชาการ",
    summary: "วางแผน ประสานเครื่องมือ สร้างงาน และสรุปผลครบวงจร",
    bestFor: "งานหลายรูปแบบที่ต้องรวมผลลัพธ์",
    color: "#51a9ff",
    glow: "rgba(81, 169, 255, .34)",
  },
  {
    name: "Claude",
    monogram: "C",
    role: "ผู้ตรวจทาน",
    summary: "อ่านเอกสารยาว ตรวจเหตุผล ความสอดคล้อง และคุณภาพงาน",
    bestFor: "เอกสารยาว การทบทวน และโค้ด",
    color: "#ffc44f",
    glow: "rgba(255, 196, 79, .28)",
  },
  {
    name: "Gemini",
    monogram: "✦",
    role: "ผู้เชี่ยวชาญมัลติโมดัล",
    summary: "เข้าใจภาพ วิดีโอ เสียง และทำงานกับระบบนิเวศ Google",
    bestFor: "สื่อหลายชนิดและงานภาพ–เสียง",
    color: "#a77cff",
    glow: "rgba(167, 124, 255, .3)",
  },
  {
    name: "Kimi",
    monogram: "K",
    role: "หน่วยจีนและวิจัย",
    summary: "ค้นคว้าเอกสารยาว งานภาษาจีน และสร้างร่างหลายรูปแบบ",
    bestFor: "วิจัยจีนและงานข้อมูลปริมาณมาก",
    color: "#8bdc63",
    glow: "rgba(139, 220, 99, .28)",
  },
  {
    name: "GLM",
    monogram: "GL",
    role: "หน่วยจีนและระบบเปิด",
    summary: "งานภาษาจีน การวิจัย OCR, RAG และระบบที่ควบคุมเอง",
    bestFor: "จีน เอกสาร และระบบภายใน",
    color: "#43d9ee",
    glow: "rgba(67, 217, 238, .28)",
  },
  {
    name: "DeepSeek",
    monogram: "D",
    role: "เครื่องยนต์คุ้มค่า",
    summary: "เหตุผล โค้ด และประมวลผลงานจำนวนมากอย่างคุ้มต้นทุน",
    bestFor: "งาน bulk, coding และระบบเบื้องหลัง",
    color: "#ff944d",
    glow: "rgba(255, 148, 77, .3)",
  },
  {
    name: "Qwen",
    monogram: "Q",
    role: "เครื่องยนต์ท้องถิ่น",
    summary: "รองรับหลายภาษา หลายสื่อ และเลือกขนาดให้เหมาะกับฮาร์ดแวร์",
    bestFor: "Local AI และงานที่ต้องคุมข้อมูล",
    color: "#ff6fae",
    glow: "rgba(255, 111, 174, .3)",
  },
];

export const routes = [
  ["สรุปผู้บริหารภาษาไทย", "GPT", "Claude"],
  ["เอกสารยาว / ตรวจข้อขัดแย้ง", "Claude", "GPT"],
  ["Coding / CLI", "Claude · GPT", "DeepSeek"],
  ["ภาพ · วิดีโอ · เสียง", "Gemini", "GPT"],
  ["OSINT จีน / ข้อมูลจีน", "Kimi", "GLM · Qwen"],
  ["ประมวลผลจำนวนมาก", "DeepSeek", "GLM · Qwen"],
  ["Local / Private AI", "Qwen", "GLM · DeepSeek"],
];
